### PR TITLE
Lab2

### PR DESCRIPTION
**Pull request by axross**
```
$ java lab2.Driver
Some awesome country Canada has 10 provinces: Ontario, Quebec, Nova Scotia, New Brunswick, Manitoba, British Columbia, Prince Edward Island, Saskatchewan, Alberta and Newfoundland and Labrador

Anyway, here is the detail of 10 provinces:
The capital of Ontario (pop. 13 million) is Toronto.
The capital of Quebec (pop. 8 million) is Quebec City.
The capital of Nova Scotia (pop. 1 million) is Halifax.
The capital of New Brunswick (pop. 1 million) is Fredericton.
The capital of Manitoba (pop. 1 million) is Winnipeg.
The capital of British Columbia (pop. 5 million) is Victoria.
The capital of Prince Edward Island (pop. 0 million) is Charlottetown.
The capital of Saskatchewan (pop. 1 million) is Regina.
The capital of Alberta (pop. 4 million) is Edmonton.
The capital of Newfoundland and Labrador (pop. 0 million) is St. John's.

So, Canada has 3 provinces that population is greater than 2 million and less than 10 million.
```

### CODE REVIEW

**Comment by axross** [comment]
@itzderr Could you go over the changes? Thanks!

**Comment by axross** [comment]
@itzderr Could you go over the changes? Thanks!

**Review by itzderr — APPROVED** [review]
👍

**Comment by axross** [comment]
Thank you!

**Pull request merged**
